name: Build Windows KeePassXC

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Clone and Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DWITH_XC_ALL=ON -DWITH_XC_NETWORKING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" ..

      - name: Build with Ninja
        run: |
          cd build
          ninja

      - name: Package
        run: |
          cd build
          cpack -G ZIP

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KeePassXC-Windows-NoNetwork
          path: build/*.zip
